"""Tests for recce.services.imap.

Fixtures are RFC-derived: every server reply is a raw byte string copied from
RFC 3501 (IMAP4rev1) / RFC 2971 (ID) / RFC 4505 (ANONYMOUS) / RFC 2195
(CRAM-MD5) response examples, not constructed by calling the module's own
encoder.
"""
from __future__ import annotations

import socketserver
import threading

from recce.services import imap
from recce.core.models import Host, Port


# --- RFC-derived wire fixtures ---------------------------------------------
# Every literal below is the byte-for-byte shape that appears in the cited
# section of the protocol RFC (or the Dovecot / Cyrus server output that
# matches it). None is generated by calling into recce.services.imap.

# RFC 3501 §7.1: `* OK [CAPABILITY ...] IMAP4rev1 server ready`
GREETING_STARTTLS_DISABLED = (
    b"* OK [CAPABILITY IMAP4rev1 STARTTLS LOGINDISABLED ID"
    b" AUTH=PLAIN AUTH=LOGIN] Dovecot ready.\r\n"
)
# Cleartext, LOGIN allowed.
GREETING_PLAIN_LOGIN = (
    b"* OK [CAPABILITY IMAP4rev1 ID AUTH=PLAIN AUTH=LOGIN AUTH=CRAM-MD5]"
    b" Dovecot ready.\r\n"
)
# RFC 3501 §7.1.4: PREAUTH greeting.
GREETING_PREAUTH = b"* PREAUTH IMAP4rev1 server logged in as smith\r\n"

# Vulnerable Dovecot fingerprint for the known-bad table.
GREETING_DOVECOT_VULN = (
    b"* OK [CAPABILITY IMAP4rev1 STARTTLS LOGINDISABLED]"
    b" Dovecot 2.3.16 ready.\r\n"
)

# RFC 3501 §7.2.1 CAPABILITY response body.
CAP_RICH = (
    b"* CAPABILITY IMAP4rev1 STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=CRAM-MD5"
    b" AUTH=DIGEST-MD5 AUTH=GSSAPI AUTH=NTLM AUTH=ANONYMOUS ID\r\n"
    b"c1 OK CAPABILITY completed\r\n"
)
CAP_MINIMAL = (
    b"* CAPABILITY IMAP4rev1 ID AUTH=PLAIN\r\n"
    b"c1 OK CAPABILITY completed\r\n"
)
CAP_STARTTLS_LOGINDISABLED = (
    b"* CAPABILITY IMAP4rev1 STARTTLS LOGINDISABLED ID AUTH=PLAIN\r\n"
    b"c1 OK CAPABILITY completed\r\n"
)

# RFC 2971 §3.3: ID response shape.
ID_DOVECOT = (
    b'* ID ("name" "Dovecot" "version" "2.3.16" "os" "Linux")\r\n'
    b"i1 OK ID completed\r\n"
)

# RFC 3501 §6.2.3 LOGIN responses.
LOGIN_NO_INVALID = b"rp1 NO Authentication failed.\r\n"
LOGIN_NO_TLS_REQUIRED = b"rp1 NO [PRIVACYREQUIRED] Plaintext authentication disallowed.\r\n"

# RFC 4505 ANONYMOUS: server issues '+' continuation, then OK.
ANON_CONT = b"+ \r\n"
ANON_OK = b"an1 OK Anonymous logged in.\r\n"

# RFC 2195 §2 CRAM-MD5: server issues base64 challenge on '+'.
# Example challenge from RFC 2195: "<1896.697170952@postoffice.reston.mci.net>"
CRAM_CHALLENGE = (
    b"+ PDE4OTYuNjk3MTcwOTUyQHBvc3RvZmZpY2UucmVzdG9uLm1jaS5uZXQ+\r\n"
)
CRAM_ABORT_OK = b"cr1 BAD authentication aborted\r\n"


# --- fake IMAP server harness ---------------------------------------------

_TAG_PLACEHOLDERS = (b"c1 ", b"i1 ", b"rp1 ", b"an1 ", b"cr1 ",
                     b"u1 ", b"x1 ")


def _rewrite_tag(reply: bytes, tag: str) -> bytes:
    for ph in _TAG_PLACEHOLDERS:
        reply = reply.replace(ph, tag.encode() + b" ")
    return reply


class _Server:
    """Threaded loopback TCP server. `script` maps upper-case command tokens
    to a bytes reply (or callable(tag, text) -> bytes). Handles the SASL
    continuation flow: when the reply begins with `+`, the handler treats the
    NEXT client line as the SASL response and returns `script.get('_SASL')`
    (or `<tag> OK Authenticated.` by default when the response is a base64
    blob, or `<tag> BAD aborted.` when the response is `*`).
    """

    def __init__(self, greeting: bytes, script: dict):
        self.greeting = greeting
        self.script = script
        outer = self

        class H(socketserver.StreamRequestHandler):
            def handle(self):
                self.wfile.write(outer.greeting)
                self.wfile.flush()
                pending_tag = None    # SASL continuation active for this tag
                while True:
                    line = self.rfile.readline()
                    if not line:
                        return
                    text = line.decode("latin-1", "replace").rstrip("\r\n")
                    if pending_tag is not None:
                        tag, pending_tag = pending_tag, None
                        sasl_reply = outer.script.get("_SASL")
                        if callable(sasl_reply):
                            reply = sasl_reply(tag, text)
                        elif sasl_reply is not None:
                            reply = _rewrite_tag(sasl_reply, tag)
                        else:
                            reply = (f"{tag} BAD aborted\r\n".encode()
                                     if text.strip() == "*"
                                     else f"{tag} OK Authenticated.\r\n".encode())
                        self.wfile.write(reply)
                        self.wfile.flush()
                        continue
                    parts = text.split(None, 2)
                    if len(parts) < 2:
                        continue
                    tag, cmd = parts[0], parts[1].upper()
                    reply = outer.script.get(cmd)
                    if callable(reply):
                        reply = reply(tag, text)
                    if reply is None:
                        reply = f"{tag} BAD unknown\r\n".encode()
                    else:
                        reply = _rewrite_tag(reply, tag)
                    self.wfile.write(reply)
                    self.wfile.flush()
                    if reply.strip().startswith(b"+"):
                        pending_tag = tag
                    if cmd == "LOGOUT":
                        return

        self.srv = socketserver.ThreadingTCPServer(("127.0.0.1", 0), H)
        self.srv.daemon_threads = True
        threading.Thread(target=self.srv.serve_forever, daemon=True).start()
        self.port = self.srv.server_address[1]

    def close(self):
        self.srv.shutdown()
        self.srv.server_close()


# --- probe: capability / greeting parsing ---------------------------------

def test_probe_parses_capabilities_and_starttls_from_greeting():
    srv = _Server(GREETING_STARTTLS_DISABLED, {
        "CAPABILITY": CAP_STARTTLS_LOGINDISABLED,
        "ID": ID_DOVECOT,
        # Pre-TLS LOGIN advertised as disabled -> refuse with the RFC-shaped
        # NO citing TLS. Downgrade-check should NOT fire.
        "LOGIN": LOGIN_NO_TLS_REQUIRED,
        "LOGOUT": b"x1 OK logout\r\n",
    })
    try:
        pr = imap.probe("127.0.0.1", srv.port, timeout=3)
    finally:
        srv.close()
    assert pr["reachable"]
    assert pr["starttls"] is True
    assert pr["logindisabled"] is True
    assert "PLAIN" in pr["sasl"]
    assert pr["plaintext_login"] == "rejected"
    assert pr["starttls_downgrade"] is False
    assert pr["product"].lower().startswith("dovecot")


def test_probe_flags_plaintext_login_when_no_starttls():
    srv = _Server(GREETING_PLAIN_LOGIN, {
        "CAPABILITY": CAP_MINIMAL,
        "ID": ID_DOVECOT,
        # Server processes the LOGIN and returns a generic "authentication
        # failed" — plaintext auth path IS open.
        "LOGIN": LOGIN_NO_INVALID,
        "LOGOUT": b"x1 OK logout\r\n",
    })
    try:
        pr = imap.probe("127.0.0.1", srv.port, timeout=3)
    finally:
        srv.close()
    assert pr["reachable"]
    assert pr["starttls"] is False
    assert pr["logindisabled"] is False
    assert pr["plaintext_login"] == "accepted"


def test_probe_detects_preauth_greeting():
    srv = _Server(GREETING_PREAUTH, {
        "CAPABILITY": CAP_MINIMAL,
        "LOGOUT": b"x1 OK logout\r\n",
    })
    try:
        pr = imap.probe("127.0.0.1", srv.port, timeout=3)
    finally:
        srv.close()
    assert pr["reachable"]
    assert pr["preauth"] is True


def test_probe_captures_anonymous_and_cram_challenge():
    srv = _Server(GREETING_PLAIN_LOGIN, {
        "CAPABILITY": CAP_RICH,
        "ID": ID_DOVECOT,
        "LOGIN": LOGIN_NO_INVALID,
        "AUTHENTICATE": lambda tag, text: (
            ANON_CONT if "ANONYMOUS" in text.upper()
            else CRAM_CHALLENGE
        ),
        "LOGOUT": b"x1 OK logout\r\n",
    })
    try:
        pr = imap.probe("127.0.0.1", srv.port, timeout=3)
    finally:
        srv.close()
    assert "ANONYMOUS" in pr["sasl"]
    assert pr["anonymous"] is True                      # server returned tagged OK
    assert pr["cram_md5_challenge"].startswith("PDE4OTYu")
    assert pr["digest_md5_challenge"] != ""


# --- probe: known-bad banner match ----------------------------------------

def test_probe_matches_dovecot_known_bad_banner():
    srv = _Server(GREETING_DOVECOT_VULN, {
        "CAPABILITY": CAP_STARTTLS_LOGINDISABLED,
        "ID": b"i1 NO ID not supported\r\n",
        "LOGIN": LOGIN_NO_TLS_REQUIRED,
        "LOGOUT": b"x1 OK logout\r\n",
    })
    try:
        pr = imap.probe("127.0.0.1", srv.port, timeout=3)
    finally:
        srv.close()
    assert pr["reachable"]
    assert pr["product"].lower().startswith("dovecot")
    # Simulate the host-shape findings() sees.
    h = Host(ip="127.0.0.1",
             ports=[Port(portid=srv.port, service="imap", state="open")])
    titles = {f["title"] for f in imap.findings(
        [h], {("127.0.0.1", srv.port): pr})}
    assert any("Dovecot" in t and "CVE" in t for t in titles)


# --- findings: mapping probe results to findings --------------------------

def _host_at(port: int) -> Host:
    return Host(ip="10.0.0.9",
                ports=[Port(portid=port, service="imap", state="open")])


def test_findings_emits_all_key_kinds_for_worst_case_probe():
    h = _host_at(143)
    pr = {
        "reachable": True, "port": 143,
        "banner": "* OK Dovecot ready.",
        "preauth": False,
        "capabilities": ["IMAP4rev1", "ID", "AUTH=PLAIN", "AUTH=CRAM-MD5",
                         "AUTH=GSSAPI", "AUTH=ANONYMOUS", "AUTH=NTLM"],
        "starttls": False, "logindisabled": False,
        "sasl": ["PLAIN", "CRAM-MD5", "GSSAPI", "ANONYMOUS", "NTLM"],
        "id": {"name": "Dovecot", "version": "2.3.16"},
        "product": "Dovecot", "version": "2.3.16",
        "plaintext_login": "accepted",
        "anonymous": True,
        "starttls_downgrade": False,
        "cram_md5_challenge": "PDE4OTYu",
        "digest_md5_challenge": "",
        "enum": {"distinguishes": True, "existing": ["root", "postmaster"],
                 "responses": {}},
        "credentialed": {"login": True, "user": "mail", "default_creds": True,
                         "mailboxes": {"list": ['(\\HasNoChildren) "/" "INBOX"'],
                                        "lsub": [], "namespace": ""},
                         "loot": ["[password reset] seq=42 SUBJECT: password reset"]},
    }
    fs = imap.findings([h], {("10.0.0.9", 143): pr})
    kinds = {f["kind"] for f in fs}
    for expected in (
        "imap_no_starttls",
        "imap_login_plaintext_allowed",
        "imap_sasl_mechanisms",
        "imap_gssapi_relay",
        "imap_anonymous_allowed",
        "imap_offline_crack_channel",
        "imap_id_disclosure",
        "imap_version_cve",
        "imap_user_enum",
        "imap_default_creds",
        "imap_mailbox_access",
        "imap_loot_hits",
    ):
        assert expected in kinds, f"missing {expected}: got {kinds}"


def test_findings_emits_preauth_critical():
    h = _host_at(143)
    pr = {"reachable": True, "port": 143, "banner": "* PREAUTH ...",
          "preauth": True, "capabilities": [], "starttls": False,
          "logindisabled": False, "sasl": [], "id": {},
          "product": "", "version": "", "plaintext_login": "",
          "anonymous": False, "starttls_downgrade": False,
          "cram_md5_challenge": "", "digest_md5_challenge": ""}
    fs = imap.findings([h], {("10.0.0.9", 143): pr})
    preauth = [f for f in fs if f["kind"] == "imap_preauth_greeting"]
    assert preauth and preauth[0]["severity"] == "critical"


def test_findings_starttls_downgrade_fires_when_logindisabled_lied():
    h = _host_at(143)
    pr = {"reachable": True, "port": 143, "banner": "* OK ...",
          "preauth": False,
          "capabilities": ["IMAP4rev1", "STARTTLS", "LOGINDISABLED"],
          "starttls": True, "logindisabled": True,
          "sasl": [], "id": {}, "product": "", "version": "",
          "plaintext_login": "accepted", "anonymous": False,
          "starttls_downgrade": True,
          "cram_md5_challenge": "", "digest_md5_challenge": ""}
    fs = imap.findings([h], {("10.0.0.9", 143): pr})
    assert any(f["kind"] == "imap_starttls_downgrade" for f in fs)


def test_findings_on_993_downgrades_plain_severity_to_low():
    h = _host_at(993)
    pr = {"reachable": True, "port": 993, "banner": "* OK ready",
          "preauth": False, "capabilities": ["AUTH=PLAIN"],
          "starttls": False, "logindisabled": False,
          "sasl": ["PLAIN"], "id": {}, "product": "", "version": "",
          "plaintext_login": "", "anonymous": False,
          "starttls_downgrade": False,
          "cram_md5_challenge": "", "digest_md5_challenge": ""}
    fs = imap.findings([h], {("10.0.0.9", 993): pr})
    plain = [f for f in fs if f["kind"] == "imap_sasl_mechanisms"]
    assert plain and plain[0]["severity"] == "low"
    # No cleartext / no-starttls finding on 993 - implicit TLS is fine.
    assert not any(f["kind"] == "imap_no_starttls" for f in fs)


def test_findings_to_vulns_source_and_severity():
    h = _host_at(143)
    pr = {"reachable": True, "port": 143, "banner": "* OK ready",
          "preauth": False, "capabilities": [], "starttls": False,
          "logindisabled": False, "sasl": [], "id": {}, "product": "",
          "version": "", "plaintext_login": "accepted", "anonymous": False,
          "starttls_downgrade": False,
          "cram_md5_challenge": "", "digest_md5_challenge": ""}
    fs = imap.findings([h], {("10.0.0.9", 143): pr})
    by_ip = imap.findings_to_vulns(fs)
    assert "10.0.0.9" in by_ip
    assert all(v.source == "imap" for v in by_ip["10.0.0.9"])


# --- capability / SASL parsing --------------------------------------------

def test_parse_capabilities_unions_bracket_and_untagged():
    data = (
        b"* OK [CAPABILITY IMAP4rev1 STARTTLS AUTH=PLAIN] Dovecot ready.\r\n"
        b"* CAPABILITY IMAP4rev1 AUTH=LOGIN AUTH=CRAM-MD5\r\n"
    )
    caps = imap._parse_capabilities(data)
    assert "STARTTLS" in caps and "AUTH=CRAM-MD5" in caps and "AUTH=LOGIN" in caps
    mechs = imap._sasl_mechs(caps)
    assert set(mechs) >= {"PLAIN", "LOGIN", "CRAM-MD5"}


def test_parse_id_returns_dict():
    data = b'* ID ("name" "Dovecot" "version" "2.3.16" "os" "Linux")\r\n'
    assert imap._parse_id(data) == {"name": "Dovecot", "version": "2.3.16", "os": "Linux"}


# --- is_imap classifier ---------------------------------------------------

def test_is_imap_respects_open_state_and_port():
    assert imap.is_imap(Port(portid=143, service="imap", state="open"))
    assert imap.is_imap(Port(portid=993, service="imaps", state="open"))
    assert not imap.is_imap(Port(portid=143, service="imap", state="closed"))
    assert not imap.is_imap(Port(portid=8080, service="http", state="open"))


# --- user-enum via monkeypatched socket ------------------------------------

def test_enum_users_via_monkeypatched_socket(monkeypatch):
    """LOGIN responses differ per user; enum_users detects the asymmetry."""
    valid = {"root", "postmaster"}

    class _FakeSock:
        def __init__(self, user_line: bytes):
            self._buf = b"* OK ready\r\n"
            self._reply_login = user_line

        def settimeout(self, _t): pass

        def sendall(self, data: bytes):
            if data.upper().startswith(b"U1 LOGIN"):
                self._buf += self._reply_login
            elif data.upper().startswith(b"X1 LOGOUT"):
                self._buf += b"x1 OK logout\r\n"

        def recv(self, n: int) -> bytes:
            out, self._buf = self._buf[:n], self._buf[n:]
            return out or b""

        def close(self): pass

    def fake_open(ip, port, timeout):
        # Peek at the pending username by scheduling a socket that answers
        # per user. We stash which user we are on via a mutable counter.
        u = _fake_open.next_user()
        line = b"u1 NO OK\r\n" if u in valid else b"u1 NO Authentication failed.\r\n"
        return _FakeSock(line)

    class _Counter:
        def __init__(self, users): self.users = list(users); self.i = 0
        def next_user(self):
            u = self.users[self.i % len(self.users)]
            self.i += 1
            return u

    # 1 valid vs 3 invalid: a clean majority so `distinguishes` isn't ambiguous.
    users = ["root", "alice", "bob", "carol"]
    valid = {"root"}
    _fake_open = _Counter(users)
    monkeypatch.setattr(imap, "_open_socket", fake_open)

    result = imap.enum_users("127.0.0.1", 143, users=users, timeout=1)
    assert result["distinguishes"] is True
    assert set(result["existing"]) == valid
